package org.emf_mps.importer.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;

public class Importer_ApplicationPlugin extends BaseApplicationPlugin {
  private PluginId myId = PluginId.getId("org.emf_mps.importer");
  public Importer_ApplicationPlugin() {
  }
  public PluginId getId() {
    return myId;
  }
  public void createGroups() {
    // actions w/o parameters 
    addAction(new importEcoreAction_Action());
    // groups 
    addGroup(new importActionGroup_ActionGroup());
  }
  public void adjustRegularGroups() {
    insertGroupIntoAnother(importActionGroup_ActionGroup.ID, "EditorPopup_ActionGrouprefactoring", null);
  }
}
