package org.emf_mps.importer.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;

public class importActionGroup_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "org.emf_mps.importer.plugin.importActionGroup_ActionGroup";
  public importActionGroup_ActionGroup() {
    super("importActionGroup", ID);
    this.setIsInternal(false);
    this.setPopup(false);
    importActionGroup_ActionGroup.this.addAction("org.emf_mps.importer.plugin.importEcoreAction_Action");
  }
}
