package org.emf_mps.importer.plugin;

/*Generated by MPS */


public class LazyClassEnumReference {
  /*package*/ String name;
  public LazyClassEnumReference(String name) {
    this.name = name;
  }
}
