package org.emf_mps.importer.plugin;

/*Generated by MPS */


public class LazyLinkDeclaration {
  /*package*/ String cardinality;
  /*package*/ String metaclass;
  /*package*/ String name;


  public String getCardinality() {
    return cardinality;
  }
  public void setCardinality(String cardinality1) {
    cardinality = cardinality1;
  }
  public String getMetaclass() {
    return metaclass;
  }
  public void setMetaclass(String metaclass1) {
    metaclass = metaclass1;
  }
  public String getName() {
    return name;
  }
  public void setName(String name1) {
    name = name1;
  }
}
