package org.kriTest.Plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;

public class Plugin_ApplicationPlugin extends BaseApplicationPlugin {
  private PluginId myId = PluginId.getId("org.kriTest.Plugin");
  public Plugin_ApplicationPlugin() {
  }
  public PluginId getId() {
    return myId;
  }
  public void createGroups() {
    // actions w/o parameters 
    addAction(new triggerAction_Action());
    // groups 
    addGroup(new testActionGroup_ActionGroup());
  }
  public void adjustRegularGroups() {
    insertGroupIntoAnother(testActionGroup_ActionGroup.ID, "EditorPopup_ActionGrouprefactoring", null);
  }
}
