package org.kriTest.Plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.tool.GeneratedTool;
import javax.swing.Icon;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.wm.ToolWindowAnchor;
import javax.swing.JComponent;
import javax.swing.JFileChooser;

public class SVgViewer_Tool extends GeneratedTool {
  private static final Icon ICON = null;
  public SVgViewer_Tool(Project project) {
    super(project, "Visualisation", null, ICON, ToolWindowAnchor.RIGHT, false);
  }
  public JComponent getComponent() {
    JFileChooser filechooser = new JFileChooser();
    filechooser.setName("Ecore Importer");
    return filechooser;
  }
}
