package org.kriTest.Plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;

public class testActionGroup_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "org.kriTest.Plugin.plugin.testActionGroup_ActionGroup";
  public testActionGroup_ActionGroup() {
    super("testActionGroup", ID);
    this.setIsInternal(false);
    this.setPopup(false);
    testActionGroup_ActionGroup.this.addAction("org.kriTest.Plugin.plugin.triggerAction_Action");
  }
}
